### ISSUE TITLE
Problems Running start.cmd

### ISSUE THREAD

**Issue by mflyskym1** [hollowaykeanho/Upscaler#65] opened 2024-02-02 08:01 UTC
# Question
```
Dear friend, I followed your instructions and after configuring the system environment variables, when running start.cmd, the following error message appeared. I don’t know how to solve it. Please provide help. Thank you!

.................................................
C:\AI视频放大\upscaler main\main>start.cmd

C:\AI视频放大\upscaler main\main>echo  #   1>nul  & GOTO WINDOWS   & rem#
Get-Help : 找不到接受实际参数“main\main\init\windows.ps1”的位置形式参数。
所在位置 行:1 字符: 1
+ Get-Help C:\AI视频放大\upscaler main\main\init\windows.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Help]，ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.GetHelpCommand

 
Available Models:
upscayl-hfa2k
upscayl-lsdir-4x-compact-c3
upscayl-lsdir-4x-plus-c
upscayl-lsdir
upscayl-nmkd-4x-siax-200k
upscayl-nmkd-4x-superscale-sd-178000-g
upscayl-nomos-4x-8k-sc
upscayl-realesrgan-x4-general-wdn-v3
upscayl-realesrgan-x4plus-anime
upscayl-realesrgan-x4plus-v3
upscayl-realesrgan-x4plus
upscayl-remacri
upscayl-ultramix_balanced
upscayl-ultrasharp-v2
upscayl-ultrasharp
upscayl-uniscale-restore
xintao-realesr-animevideo-x2-v3
xintao-realesr-animevideo-x3-v3
xintao-realesr-animevideo-x4-v3
xintao-realesrgan-x4plus-anime
xintao-realesrgan-x4plus

**Comment by Joly0** [comment] 2024-02-02 09:07
Hey, can you give an explanation, what you issue is? I can see, that you are basically just running "./start.cmd" without any parameters, which doesnt work. You have to provide some required parameters

**Comment by hollowaykeanho** [comment] 2024-02-08 03:16
@mflyskym1 您好。那个问题其实是找不到代码库里的 `init\` 文件夹。您可以重新下载一次并且放入在`start.cmd` 隔壁然后再试试。

![2024-02-08_11-14](https://github.com/hollowaykeanho/Upscaler/assets/7259572/0ad47c2d-50c7-4631-8724-4fe79ae6f68a)

 
-----

(Translate to English)

Good day! The bug is caused by the missing `init\` directory. You may down the program again and place it next to `start.cmd` and retry.

**Comment by hollowaykeanho** [comment] 2024-02-10 00:39
如今我们还没收到您的回复，那我们先把这个档案总结吧。如果还有询问需求，您可以打开新的档案吧。

---

(Translate to English)

To date we haven't receive any replies from you, in that case, we're closing this case. If there are further inquiries, please open a new ticket.

**Closed by hollowaykeanho** 2024-02-10 00:39 UTC
Labels: Question, Discussion
